// All inline styles. CSS custom properties (--brand, --ink, etc.) are set on
// `root` and cascade down to every child component.
export const styles = {
  root: {
    "--brand": "#f6c63c",
    "--brand-deep": "#e0a91b",
    "--ink": "#4a4023",
    "--good": "#5cb85c",
    "--mid": "#f0a93b",
    "--bad": "#ef6f6f",
    minHeight: "100vh",
    width: "100%",
    background: "linear-gradient(160deg, #fffdf2 0%, #fff7d6 48%, #fef0c4 100%)",
    fontFamily: "'Quicksand', sans-serif",
    color: "var(--ink)",
    position: "relative",
    overflow: "hidden",
    padding: "20px 0 50px",
  },
  blobA: {
    position: "absolute",
    top: -90,
    right: -70,
    width: 280,
    height: 280,
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(255,221,99,.55), transparent 70%)",
    filter: "blur(10px)",
    pointerEvents: "none",
  },
  blobB: {
    position: "absolute",
    bottom: -100,
    left: -80,
    width: 300,
    height: 300,
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(250,196,60,.4), transparent 70%)",
    filter: "blur(10px)",
    pointerEvents: "none",
  },
  shell: {
    maxWidth: 540,
    margin: "0 auto",
    padding: "0 20px",
    position: "relative",
    zIndex: 1,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 22,
  },
  brand: { display: "flex", alignItems: "center", gap: 12 },
  logo: {
    fontSize: 26,
    width: 50,
    height: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#fff",
    borderRadius: 18,
    boxShadow: "0 8px 20px -8px rgba(224,169,27,.55)",
  },
  brandName: {
    fontFamily: "'Baloo 2', cursive",
    fontWeight: 800,
    fontSize: 22,
    lineHeight: 1.1,
  },
  brandSub: {
    fontSize: 11,
    color: "#a8985f",
    letterSpacing: 1,
    textTransform: "uppercase",
    fontWeight: 600,
  },
  streak: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#fff",
    padding: "8px 14px",
    borderRadius: 999,
    boxShadow: "0 8px 20px -10px rgba(224,169,27,.5)",
  },
  fire: { fontSize: 17 },
  streakNum: {
    fontFamily: "'Baloo 2', cursive",
    fontWeight: 800,
    fontSize: 18,
    color: "#e0951b",
  },
  controls: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "space-between",
    marginBottom: 18,
  },
  pills: { display: "flex", gap: 7 },
  pill: {
    fontFamily: "'Quicksand', sans-serif",
    fontWeight: 700,
    fontSize: 13,
    padding: "9px 14px",
    borderRadius: 999,
    border: "2px solid transparent",
    background: "#fff",
    color: "#9a8a52",
    cursor: "pointer",
    boxShadow: "0 4px 12px -6px rgba(224,169,27,.4)",
  },
  pillActive: {
    background: "var(--brand)",
    color: "#5a4a14",
    boxShadow: "0 6px 16px -6px rgba(224,169,27,.85)",
  },
  select: {
    fontFamily: "'Quicksand', sans-serif",
    fontWeight: 600,
    fontSize: 13,
    padding: "9px 16px",
    borderRadius: 999,
    border: "2px solid #f4e8b8",
    background: "#fff",
    color: "var(--ink)",
    cursor: "pointer",
    appearance: "none",
    WebkitAppearance: "none",
    backgroundImage:
      "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath d='M2 4l4 4 4-4' stroke='%239a8a52' stroke-width='2' fill='none' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E\")",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 20px center",
    paddingRight: "40px",
  },
  card: {
    background: "#fff",
    borderRadius: 28,
    padding: "26px 26px 30px",
    marginBottom: 18,
    boxShadow: "0 20px 50px -24px rgba(224,169,27,.5)",
    border: "2px solid #fbf1cc",
    position: "relative",
  },
  cardTop: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  },
  badge: {
    fontFamily: "'Baloo 2', cursive",
    fontWeight: 700,
    fontSize: 13,
    color: "#5a4a14",
    background: "var(--brand)",
    padding: "3px 11px",
    borderRadius: 999,
  },
  hint: {
    fontSize: 12,
    fontWeight: 600,
    color: "#b5882a",
    background: "#fdf3d2",
    padding: "4px 11px",
    borderRadius: 999,
  },
  viWrap: { position: "relative", paddingLeft: 6 },
  vi: {
    fontFamily: "'Baloo 2', cursive",
    fontWeight: 600,
    fontSize: 26,
    lineHeight: 1.35,
    margin: 0,
    position: "relative",
  },
  input: {
    width: "100%",
    padding: "16px 18px",
    fontSize: 16,
    fontFamily: "'Quicksand', sans-serif",
    fontWeight: 500,
    border: "2px solid #f4e8b8",
    borderRadius: 20,
    background: "#fff",
    color: "var(--ink)",
    resize: "vertical",
    lineHeight: 1.5,
    boxShadow: "0 8px 24px -16px rgba(224,169,27,.5)",
  },
  actions: { display: "flex", gap: 10, marginTop: 14 },
  btn: {
    fontFamily: "'Baloo 2', cursive",
    fontSize: 16,
    fontWeight: 700,
    padding: "13px 22px",
    borderRadius: 16,
    border: "none",
    cursor: "pointer",
  },
  btnPrimary: {
    flex: 1,
    background: "var(--brand)",
    color: "#5a4a14",
    boxShadow: "0 10px 24px -10px rgba(224,169,27,.9)",
  },
  btnGhost: {
    background: "#fff",
    color: "#9a8a52",
    border: "2px solid #f4e8b8",
  },
  kbd: {
    fontSize: 12,
    color: "#c4b483",
    marginTop: 16,
    textAlign: "center",
    fontWeight: 500,
  },
  error: {
    marginTop: 16,
    padding: 14,
    borderRadius: 16,
    background: "#fdeeee",
    color: "#d14343",
    fontSize: 14,
    fontWeight: 600,
    textAlign: "center",
  },
  result: {
    marginTop: 18,
    padding: "24px 22px",
    borderRadius: 28,
    background: "#fff",
    boxShadow: "0 24px 60px -28px rgba(224,169,27,.55)",
    border: "2px solid #fbf1cc",
  },
  scoreRow: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    marginBottom: 16,
  },
  scoreCircle: {
    width: 74,
    height: 74,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    boxShadow: "0 10px 22px -10px rgba(0,0,0,.2)",
  },
  scoreNum: {
    fontFamily: "'Baloo 2', cursive",
    fontWeight: 800,
    fontSize: 30,
    color: "#fff",
  },
  verdict: {
    fontFamily: "'Baloo 2', cursive",
    fontWeight: 700,
    fontSize: 21,
    lineHeight: 1.2,
  },
  scoreSub: {
    fontSize: 12,
    color: "#a8985f",
    fontWeight: 600,
    marginTop: 2,
  },
  feedback: {
    fontSize: 15.5,
    lineHeight: 1.6,
    margin: "0 0 14px",
    fontWeight: 500,
    color: "#6b5f38",
  },
  errors: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 16 },
  errorChip: {
    fontSize: 12.5,
    fontWeight: 600,
    padding: "7px 13px",
    background: "#fdeeee",
    color: "#d14343",
    borderRadius: 999,
  },
  correctionBox: {
    padding: "16px 18px",
    borderRadius: 18,
    background: "linear-gradient(135deg, #f3fbe9, #fdfce9)",
    border: "2px solid #dcefc0",
  },
  correctionLabel: {
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "#5a9b2e",
    marginBottom: 6,
    fontWeight: 700,
  },
  correction: {
    fontFamily: "'Baloo 2', cursive",
    fontSize: 17,
    lineHeight: 1.45,
    fontWeight: 600,
    color: "#3f6b1e",
  },
};

export const scoreColor = (s) =>
  s >= 80 ? "var(--good)" : s >= 50 ? "var(--mid)" : "var(--bad)";

export const scoreFace = (s) => (s >= 80 ? "🎉" : s >= 50 ? "🙂" : "💪");
